version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:45"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: solc
    versions:
    - 0.8.1
    - 0.8.2
    - 0.8.3
  - dependency-name: typescript
    versions:
    - 3.9.9
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: web3
    versions:
    - 1.3.3
    - 1.3.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: mocha
    versions:
    - 6.2.3
  rebase-strategy: disabled
  registries:
  - npm-registry-registry-npmjs-org
